# Generated by Django 2.2.10 on 2020-03-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couverture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couverture', models.ImageField(upload_to='images/Couverture')),
                ('artiste', models.CharField(max_length=120)),
                ('date', models.CharField(max_length=60)),
                ('music', models.FileField(max_length=150, upload_to='')),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_apdate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': ' ',
                'verbose_name_plural': ' ',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/Playlist')),
                ('titre', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('date', models.CharField(max_length=50)),
                ('lien', models.CharField(max_length=150)),
                ('video', models.URLField(max_length=150)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_apdate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': ' ',
                'verbose_name_plural': ' ',
            },
        ),
    ]
